### ISSUE TITLE
Building the house and unable to use the furnace.

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#1]
I did the quest and got the House blueprint which attempted to place down. The configuration popped up and I had difficulty anchoring it, I thought I had configuration to be a larger house (it had sliders to adjust house size) and then I realized that the house would take out part of my starter shack that had items in it, so I dismissed the preview. When I put it down again and when to configure it again, the option to make the house larger disappeared and in its place was the color of windows. I went ahead and placed it. 
I went to smelt some zombie flesh and was unable to use the furnace. Not to big of deal...just need to pickaxe it and place it back down, but I know some people will have a cow about it. Maybe a blurb somewhere to say to pick it up and put it back down.

**Comment by teagan75** [comment]
I have noticed that all furnaces placed by npcs or schematics do not work until broken and replaced. Since it is across the board with all mods I am thinking this is a mc1.10 issue
