### ISSUE TITLE
I had to manually complete the copper axe quest. Since it was the item  that was involved in forcing me to use a backup, I think it was borked, but you may want to check it to make sure of it.

### ISSUE THREAD

**Issue by teagan75** [teagan75/Metamorphoses#10]
I had to manually complete the copper axe quest. Since it was the item  that was involved in forcing me to use a backup, I think it was borked, but you may want to check it to make sure of it.

_Originally posted by @Ladysarajane in https://github.com/teagan75/Metamorphoses/issues/8#issuecomment-502808628_

**Comment by teagan75** [comment]
Ok I set all the HF tool quests to ignore NBT data. This wills solve the
"you have to use the item for it to register" annoyance. There was a reason
I didn't do this before but it seems to have resolved itself. Will be in
next update.

**Comment by Ladysarajane** [comment]
That is good because the fishing rod when I received it  did not trigger. I used it and caught a fish and it still did not registered. I had to manually complete that quest.

**Comment by teagan75** [comment]
Hope this is fixed in v0.4.0
