### ISSUE TITLE
Plum seeds Quest

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#11]
I am attempting to do the plum seed quest. Getting 4 of them is difficult. I have made the cinderbella and made the collis seed. I planted them to get more seeds for the plum seeds, but I am having difficulty getting them to grow. I planted them at Y level 107, I water them everyday but it takes days and days for them to grow once and 9 out of 10 times, I just get a golden rod and not the seed. The plant doesn't respond to bonemeal.  I am getting frustrated with them. Cinderbella sprouts, take so much bonemeal to grow, but they do grow.  I do have on Plum seed, but again, seed drop rate so poor, I used all my bonemeal, it dropped 10 plums (although I only caught 2) and not one seed. I couldn't convert the plums to seeds.

**Comment by teagan75** [comment]
For this, I believe the only way to get more seeds is to make them. I could add a recipe to convert plums to seeds tho. It's just not supported natively through the mod

**Comment by Ladysarajane** [comment]
Yeah, but it is difficult. Keep running out of bonemeal.  Fishing bones helps some, but gads it is rough to get enough collis seeds to make them.

**Comment by teagan75** [comment]
I have an update ready to go but haven't gotten around to uploading it.
Well I am glad I waited :D

**Comment by Ladysarajane** [comment]
I'm glad too and I think I found a bug with Harvest Festival, nothing you can do about it but I was killed fighting mobs for bonemeal...and in my journal, I lost all my lore pages I had. Not the Farming one, thank goodness, but in case anyone mentions it, I haven't found a way to get them back. I don't think they mean anything other than for reading.

**Comment by teagan75** [comment]
are the pages not going into the book automatically? or the book cleared
itself?

**Comment by Ladysarajane** [comment]
Book cleared itself. No pages at all.
![2019-06-23_12 46 14](https://user-images.githubusercontent.com/34258851/59979358-ea5b1380-95b4-11e9-849f-99bb8571f6e6.png)

**Comment by teagan75** [comment]
hm that is strange. You can find the pages in the creative tab for Lore
Expansion if you want to replace them. Just hold them and right-click.

I added a script to change plums into seeds and pushed it out with update
0.4.0

**Comment by Ladysarajane** [comment]
Oh Thank you...that will help a lot with the plums. Thanks for the tip on the pages. I need to hoard those pages 🤣

**Comment by Ladysarajane** [comment]
You did push out the update?  Twitch is being slow today. 

Are vanilla fish in the pack? I am wondering if that would be good for minecolony workers to eat.

**Comment by teagan75** [comment]
I am fighting with Curse right now sigh. Something messed up on their end
and they are being ever so helpful

**Comment by Ladysarajane** [comment]
Lol....I know their help. Downloads are from them and they keep telling me twitch is responsible for the interface in downloading them. It was that the interface couldn't locate the file...I even sent them the screenshot of the error!

**Comment by Ladysarajane** [comment]
The collis seeds I found work best with agricraft watering sprinklers....Maybe instead of converting the plums to seeds, maybe a hint to use the sprinklers with the goldenrods to get the seeds to craft them?

**Comment by teagan75** [comment]
I can add a hint to use the sprinkler system. I think i will still leave the recipe for seeds in as well. Couldn't hurt.

**Comment by Ladysarajane** [comment]
No, it wouldn't hurt at all. The Minecolonies people eat the golden bread well.

**Comment by teagan75** [comment]
issue fixed in v0.4.0
