### ISSUE TITLE
Animal spawn eggs Don't work

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#12]
Built the Cowboy hut from Minecolonies...Assigned a worker, Went to use the spawn eggs that we made in the quests and I placed them...heard a moo but no cow. Tried both eggs, no deal. Restarted game, still no cow visible. I haven't built the Swineherder hut yet, to try the pigs, but I am assuming the same thing.

**Comment by teagan75** [comment]
Sigh. A command should have kicked off when you completed the spawn egg quest. I will have to check on that

**Comment by Ladysarajane** [comment]
Piggy's don't work either

**Comment by teagan75** [comment]
Can you try running these commands? Not sure if the command isn't valid or
if its messing up in the quest book

/blacklist-mob remove Cow

/blacklist-mob remove Pig

**Comment by Ladysarajane** [comment]
When I run those commands it tells me those animals are not blacklisted
![2019-06-24_09 00 32](https://user-images.githubusercontent.com/34258851/60020701-8b51d900-965e-11e9-8c81-4d1615082d6b.png)
![2019-06-24_09 01 11](https://user-images.githubusercontent.com/34258851/60020743-a290c680-965e-11e9-8057-641509d866ff.png)

**Comment by teagan75** [comment]
And yet it is lol. Can you pull out a cow spawn egg and place one? I assumed the mod just gave a way to craft Minecraft spawn eggs but maybe it changes something. 

Edit: also are any cows or pigs spawning naturally now on grass?

**Comment by teagan75** [comment]
When you ran the command did you capitalize pig and cow?

**Comment by Ladysarajane** [comment]
No, I didn't try to capitalize. I'll try that now

**Comment by Ladysarajane** [comment]
That was it...I'm sorry I didn't read your instructions well enough...I missed the capitalization. I now have cows! And I am having my first barbarian raid. Question on minecolonies....is the barracks part of the quests? 
![2019-06-24_09 59 57](https://user-images.githubusercontent.com/34258851/60025048-d7088080-9666-11e9-9ffd-7f6a1a1abe19.png)

**Comment by teagan75** [comment]
Glad it worked! Apparently that command has to be done by a player but I think I have a workaround. 

Barracks is a part of the questline. It is in the Metropolis chapter I hope I can release if Curse stops being a butt. Let me know if the barbarians become too much too soon. I can always blacklist them until later.

**Comment by Ladysarajane** [comment]
Well...I had one barbarian and he was easy for now, it never said though the raid was over, so I am assuming most of them must of despawned somewhere. Although I haven't looked at the configs to see where you have the spawn size and how many days between raids. 
Oh hint for you when placing Minecolonies buildings (I saw in your video you couldn't figure out where the doors where)...visualize the buildings in level 5. The building will still build only at level 1, but you can see were the front of the building is better. (PS Minecolonies is my favorite mod!)

 I found with the collis seeds, that using agricraft sprinklers is the answer..but it is rough lugging the water to the tower. Maybe add that info into the quest for collis seeds that they tend to grow better with sprinklers?

![2019-06-24_10 12 42](https://user-images.githubusercontent.com/34258851/60025930-a7f30e80-9668-11e9-8e9a-1f2ebf907cc6.png)

**Comment by teagan75** [comment]
I have had lots a people tell me about seeing lvl 5 of buildings hehe 😝 I can add that tip to the book np. 

You will get a water pump soon 😉

**Comment by teagan75** [comment]
I changed the raids to be 7 days apart but not sure if that change came with the current version or not.

**Comment by Ladysarajane** [comment]
Good for the water pump! A lot of the bugs in this version of Minecolonies is fixed in versions 1.12, so I hope Jerle is able to port Harvest Festival. You might want to add that if Minecolonies workers quit working and they are not asking for anything....to nudge them first...recall them to their building and if that fails...fire them wait a few seconds(till ya see their civvies on them) then rehire them. Usually then they will continue working. Also to make sure they are not hungry.  I wish you had a place to share screenshots of people's villages. That would be cool. Get good ideas on how people handle the terrain. 

I will check on the raid config...

Yes in my version it is 7 days

**Comment by teagan75** [comment]
Been fighting all afternoon with the command to allow spawns. The commands can only be run by the player and not command blocks. I found a jenky way to do it but it works. The chat will say CLICK HERE so if you click it you run the command lol. And Curse finally got back with me. Apparently the dev who made the Music mod pulled it from Curse. No more pretty music D: If you want to keep it, you will have to manually pull out ActualMusic and Embassy from the mods folder and replace them once you update the pack.

![2019-06-25_15 19 37](https://user-images.githubusercontent.com/12485764/60130597-292bcd80-975d-11e9-942f-8808e2892829.png)

**Comment by Ladysarajane** [comment]
OOOh..good hint. I like that music. If you want me to, when I get this update...I will make a new world and try out all the fixes. It will take me a while to get to the same point, but I will get there. I am in currently in the City quests. Struggling to place the smeltery correctly. I can't remember how the building looks in minecolonies to place the block down, so it won't interfere with other buildings.

**Comment by teagan75** [comment]
issue fixed in v0.4.0
