### ISSUE TITLE
How do I get the goddess flower? Version 0.4.0

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#13]
I restarted the pack to check out some of the 'changes' and the first Quest instead of being a reading checklist to obtain the lore pages it now has you getting the Goddess Flower. But the lore pages instructing you how to get the Goddess Flower is the reward.

**Comment by teagan75** [comment]
Whoops

**Comment by teagan75** [comment]
Curseforge is down so I cannot hotfix this until it is up

**Comment by Ladysarajane** [comment]
Oh...I had to find my way back into here. I couldn't click my bookmark tab....kept telling me the site was down. But I kept getting email answers....

**Comment by teagan75** [comment]
fixed in v0.4.1_hotfix
