### ISSUE TITLE
I need a Bulldozer quest

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#14]
I made the Sparks crafting table....quest picked it up without difficult. Made the stone excavator and the quest book will not recognize it. It says retrieval task, and I don't remember it doing this the first time. 
![2019-06-26_12 34 41](https://user-images.githubusercontent.com/34258851/60198880-a401f080-9810-11e9-807f-12434d978112.png)
This is the excavator I made....I made two of them. 
I tried using one and it still didn't recognize it. 

And just for giggles, In case anyone mentions it, I planted my first round turnips and watered them and when I turned around I saw this.
![2019-06-26_11 13 53](https://user-images.githubusercontent.com/34258851/60198946-c8f66380-9810-11e9-89ba-9b1f1ca71c8d.png)
Said it was a null seed
Turns out it was a large stump after I planted the turnips and watered them. It showed up the next day. 

And just for info, I did download the pack into a fresh new profile....so I have fresh files. (Plus I did add the music back in :wink:

**Comment by teagan75** [comment]
I will double check that quest since I have time today waiting for Curse to come back online lol

**Comment by Ladysarajane** [comment]
Yeah...and I was hoping to catch you so if there is a fix it will go out together.

**Comment by teagan75** [comment]
There is some weird NBT data on some of the sparks items so I just made the quest ignore it. Hopefully that will solve the issue. It's weird cause I know in my series it completed no problem.

**Comment by Ladysarajane** [comment]
Yeah, my town which I was playing before had no problem with it. I don't know what changed to make it suddenly stop recognizing it. Only difference is I have a new town and playing on a fresh set of files.

**Comment by teagan75** [comment]
0.4.1_hotfix is live - hopefully this issue is resolved

**Comment by Ladysarajane** [comment]
Started another town, this quest completed fine this time. You can close it.
