### ISSUE TITLE
Game -World slow to load, then crashing after play for about 5mins

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#15]
Since I opened the Hamlet Quest line, I have been having difficulties loading my world (It can take up to 5 mins loading it) , then after about 5mins of playing  the game people stop, but Harvest Festival time clock keeps ticking. Chests are unable to open and everything else freezes then after a min or too, Game crashes back to launcher.  This has done this 4 times today on me. I can't find a pattern to it. This is also since the hotfix update with the crashing. 
[latest.log](https://github.com/teagan75/Metamorphoses/files/3336627/latest.log)

**Comment by teagan75** [comment]
I see a lot of spamming of minecolonies stuff. I had this happen to a world too and it was minecolonies unfortunately. My buildings were too spread out I think. You can try using a minecolonies backup

**Comment by Ladysarajane** [comment]
I have a feeling I know what it is.......I think the center of the colony is messed up with the townhall. I am going to use a backup before I started  Minecolonies and try to place the townhall again. My buildings right now are close together.  So that isn't it. (I have a townhall, builder and 1 citizen hut and that is it and they are close to each other. I was wondering if it was minecolonies because when I was placing the townhall it placed before I was ready I picked it up and moved it a few blocks to the left to avoid Yullif's hut.

**Comment by teagan75** [comment]
It's generally minecolonies D:

**Comment by Ladysarajane** [comment]
It's not Minecolonies. I took it back before I even attempted to place the Townhall and the world still loads slowly and unloads slowly. It doesn't crash, but it is very very slow. I think Minecolonies caused the total crashing, but not the slowness. I started up my old world in this instance and it loaded without difficulty and unloaded without difficulty. I think my world is borked somewhere. Can't figure out what though. Do you see anything in the log? This is a log before placing townhall. (My backup)
[latest.log](https://github.com/teagan75/Metamorphoses/files/3339708/latest.log)

**Comment by teagan75** [comment]
I don't see anything in the log that identifies an issue.

**Comment by Ladysarajane** [comment]
I couldn't see anything either. I guess the only thing I can do is restart the world.
 I would love to blame the new launcher...except my old world loads fine. LOL

I do have a question...the Smeltery in minecolonies...is it a schematic you came up with? I have been trying to get a feel on how to place it down in my old world without using the wand. (You said using the wand keeps a worker from being assigned) Does it need to be up a block like the town hall?  The smeltery I see is in Schematics...I was laughing cause in level 4 a cow is part of it. Not sure how the builder is going to place a cow...but I like to see..LOL

**Comment by teagan75** [comment]
It's not my schematic but minecolonies. Its a rectangle with the opening on a long side and yes it needs to be up one block I believe.

**Comment by Ladysarajane** [comment]
It acts like it is a person's schematic and not a Minecolonies official one. Especially with the cow in it and being in the schematic file.  I know that version Minecolonies was just adding in some of the crafters. Need to check that out in my play file of The Simple Life Genesis. I think that is using the same version of Minecolonies. Any ways.....I have restarted my world (same seed). You can close this since I have decided to abandon that world as being unplayable.

**Comment by Ladysarajane** [comment]
Hold on.... I think it is the seed itself. I started the world using the seed and the first time it loaded, it loaded fine, but when I went to close it to go to lunch.....it was hanging again. When I get back to my computer I will try to start up again. And see if it hangs again.

**Comment by teagan75** [comment]
Weird it’s a seed. What biome does it start you in? Maybe too many blocks? Idk

**Comment by Ladysarajane** [comment]
My spawn point I am unsure of , but I travel to a biome that says roofed forest, but a river biome is near along with birch forest. My seed is -5258057642750732834 and I put my flower pot on x=379, y=1164, z=270  to call the goddess. Mobs are far enough away to avoid...but close enough to whack them if I want. I have 6gigs of ram assigned to minecraft. I tried to get twitch to use the old jar launcher, but it won't have it anymore...

I guess I need to go seed hunting until I find one I like again and won't crash.

**Comment by Ladysarajane** [comment]
My brother used the seed and set up near my town's coordinates and he had the same difficulties. For some reason my computer doesn't like that seed. I started another world .....and started a town and no difficulty. You can close this as this is seed related. I was just unlucky.

**Comment by teagan75** [comment]
Minecraft is weird sometimes
