### ISSUE TITLE
Fishing Rod Quest 

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#18]
The Fishing Rod Quest name is called New Quest in the Village Quest Line. It does not complete when you receive the rod. I used it to catch a fish and it still didn't complete. So I took it to the blacksmith and had it repaired and when I got it back then it completed. Is that the way it is suppose to go?

**Comment by teagan75** [comment]
No. I don’t know why it did that but I will look into it

**Comment by Ladysarajane** [comment]
Thanks...I don't remember the fishing rod having a problem previously. I am waiting to level up my axe to see if the Copper Axe quest works.

**Comment by teagan75** [comment]
I believe this happened because I switched all the tools to ignore NBT data
to fix the other issue. I will try to change this quest back to the way it
was and leave the other tool quests changed. Let me know if any others fail
as well.

**Comment by Ladysarajane** [comment]
I just did the copper axe quest and it went well as well as the hammer and the watering can copper axe quest. I haven't been able to get to  silver yet. I'm slow in mining this play through.

**Comment by teagan75** [comment]
this should be fixed for the next update

**Comment by teagan75** [comment]
Fixed in v0.4.3
