### ISSUE TITLE
Price of General Store

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#2]
I never placed Harvest festival pack before, so this is new to me. I think the price of the General Store is a little steep in starting out. My first attempting to play through the pack, I couldn't get the store until almost the middle of summer. I didn't know you could get free good turnip seeds from Jade for flowers, but that is still slow, because of all the flowercraft flowers that show up with the wand and Jade wouldn't accept 5 of those for a turnip seed.  I am slow in getting bonemeal. ( I did save one grass and put dirt around my goddess pond to grow more grass to use for spawning flowers....but still have difficulty getting enough flowers to trade...and she will give you so many then run out for a bit so using the hardy turnip seeds is really a long way to get the amt of 5k to start out.

**Comment by teagan75** [comment]
Did you get the poultry farm and/or Ranch? The products from those give money every day. Those two buildings are cheaper. The price is set with the Harvest Festival mod. This is why I give some money for completing other quests.

Another hint is to loot the chests in the new HF buildings and sell those items using the shipping bin if possible. The Ranch and Poultry buildings come with hay bales. Take those, break them down to wheat and sell/ship them.

**Comment by Ladysarajane** [comment]
Gads! Never thought of doing that those first. I will need to rewatch some of the Harvest Festival mod videos...seems like I remember them being 3k. That is why I thought you set the price on it. My loot in the HF buildings have been poor. The RPG gods surely haven't been smiling on me. All my mob spawns are mostly spiders....so plenty of string and hardly no bones or zombie flesh....I got just enough to do the helmet quest and I am still working on the armor quest.  My saving grace has it has been raining a lot so I haven't had to water my crops. I can concentrate of getting wood and cobblestone and growing apples.

**Comment by Ladysarajane** [comment]
Okay...I watch Modii's  and I watched Grimkor LP of playing with Harvest festival mod and they both had different prices....Modii's was 3K but he needed a lot more materials to build it and even Grimkor's   was 5K he need more materials for it then in Metamorphoses. So it is random from pack to pack.

**Comment by teagan75** [comment]
Huh. Never paid attention. Thought it was always the same. The Ranch and Poultry buildings have always been cheaper. Also, Farming Valley uses a older version of Harvest Festival than Metamorphoses

**Comment by Ladysarajane** [comment]
The differences could be different version related. Big question...will the minecolonies farmer be able to grow their own food? I know I can't plant the wheat seeds I obtained or potatoes etc..but I know those workers get hungry and I don't know how I will feed them yet. (I haven't placed my town hall yet.)

**Comment by teagan75** [comment]
I have been feeding them apples hehe. In another chapter, you set up vanilla/minecolony ranchers. I haven’t gotten to a point where my colonists needed food and asked for it. Pam’s Harvestcraft is in the pack and is integrated with Harvest Festival. So they may eat that food but I am unsure at this point. What I am pretty sure about is that Minecolony npcs won’t farm Harvest Festival. They may harvest the crops but they won’t replant them correctly. The meat should be good with the ranchers tho but that comes later.

**Comment by Ladysarajane** [comment]
I guess I will find out soon enough.....I know there is a mining hill for Harvest festival...but is there a way to get regular metals later in the pack for minecolonies? I know guards love iron and the sawmill guy loves iron axes. And to make racks you will need iron to make iron bars for the warehouse.
I tried digging down and all I got was wasteland to bedrock.

**Comment by teagan75** [comment]
I have scripted Harvest Festival metal to melt into normal metal bars. Iron comes from junk ore so there is plenty. Later on you will discover ore crops to add to your supply.

**Comment by Ladysarajane** [comment]
Great! I was wondering about that. Minecolonies tend to be iron hogs in general. I love playing Minecolonies in general. One of these days  I was hoping  you and Modii play CaveColonies. The new Drawven schematics on minecolonies is made for underground building.

**Comment by teagan75** [comment]
Sounds fun 😁

**Comment by Ladysarajane** [comment]
*smacks head on desk* ----You can close this...I feel stupid.....agricraft is in the pack....wheat! Money issues solved.  Couldn't figure out why Jenni would sell melon seeds if I couldn't plant them. Now I know. But I hate those weeds...

**Comment by teagan75** [comment]
Ah yes I will disable the weeds in the next update. I still don't think
minecolonies is compatible with agricraft. Plus you will need to complete
the irrigation quest before planting because farmland will not water itself
even cropstick farmland.

**Comment by teagan75** [comment]
Fair warning I may have to either disable the ability to grow wheat on crop
sticks OR add more items players must purchase at shops to balance the
pack.By summertime crops sell for more money and it becomes less an issue.
BUT if Minecolonies ends up needing wheat.....

**Comment by Ladysarajane** [comment]
No agricraft is not  compatible with Minecolonies....Yet. I do have a small wheat field with crop sticks and it is growing. I haven't opened the Irrigation quest yet. That is how I am now able to afford my buildings. The dirt does look dry, but they are growing. 

As long as I can grow wheat....I can supply the baker to make bread to deliver to the restaurant to feed workers. Really need to get that Mine hill set up.  So the miner from Minecolonies  is useless unless I just want him to mine wasteland soil to convert to dirt or use for terraforming. 
![2019-06-01_15 52 32](https://user-images.githubusercontent.com/34258851/58752976-f8ba8180-8485-11e9-9438-6a48b8917e7d.png)

**Comment by teagan75** [comment]
Yes the miner is useless and so is the farmer most likely. They are not
quests. Wheat sells for so much gold I think it will be OP to allow it to
grow on cropsticks. I may just rearrange the quests so people are forced to
buy the Ranch and Poultry Farm before the General Store and hint at taking
the haybales lol.

**Comment by Ladysarajane** [comment]
The wheat seeds I got from using bonemeal on grass. General store sells the wheat...but it takes so long to grow. Mine won't be ready until the end of summer for that wheat. Still trying to figure out the nomie? seeds. General stores sell it, I got them bonemealing, but I can't plant them on dirt or on cropsticks. What are they?

**Comment by teagan75** [comment]
Wheat takes a long time to grow because it's a huge cash crop which is why
i will be disabling it from Agricraft. Normie seeds will be used to develop
unique crops and resource crops.

**Comment by Ladysarajane** [comment]
I haven't used unique crops. There won't be a need for wheat crops for crossbreeding?  That would be my only concern with disabling it. And worms will take place of watering every day as long as they are alive? I just opened the Hamlet quest. And I see Normie seeds in the quest line now.

**Comment by teagan75** [comment]
No wheat won’t be used to crossbreed not any of the other vanilla crops. I added the AG flower seeds to Jade’s shop to offer dye. Worms will water your crops but you have to place them on an empty field before seeding. I can’t seem to get them to place down once there are plants.

**Comment by Ladysarajane** [comment]
Ah that is good to know about the worms for when I go after them. :)  When the new version comes out I will start a new world to see how that goes. I Figured out the relationships with villagers...I have recipes stacked in a chest until I can get the Cafe up.

**Comment by teagan75** [comment]
I’ve barely scratched the surface with relationships lol. I was hoping to include it in the questbook at one point

**Comment by Ladysarajane** [comment]
That might be a good ideal. You need the relationships to get recipes. Some of them hint what they love and others hint. Candice and Jim were the hardest to figure out, but she does give indirect hints with her conversations and what she gives you.

**Comment by Ladysarajane** [comment]
I Started a new world attempting to play with placing a placing the ranch/poultry farm first to get that wheat. When breaking grass after bonemealing grass I got a bamboo shoot.....converted it to seed and planted it and it is worse than wheat!

![2019-06-04_15 25 21](https://user-images.githubusercontent.com/34258851/58959402-010b0900-8773-11e9-9138-11474ccd6310.png)

And it regrows 2-3 times a day, with 4-5 obtained with each harvest so that amt if for one harvest. It is a rare drop with the grass....I only obtained one. 
I have noticed that the flower wand minecraft flowers are hard to obtain. After you get them and break them more than half of mine disappear even though I did hit their hitbox. They do not like to be harvested by the wand....that is why I bone meal grass.

**Comment by teagan75** [comment]
I have noticed that with the wand too. I have debated removing the wand and just gifting flowers occasionally. Once you make the grassy plain flowers aren’t an issue. 

The Bamboo from Harvestcraft? Seeds are not suppose to drop from grass lol

Never mind you said you converted it. Yeah I still need to lock down the configs. Working on that. Hopefully I will have an update out this week.

**Comment by Ladysarajane** [comment]
I was surprised by the bamboo...usually it is not that good of crop except to fill in for spice of life. Never dreamed it could make me rich....LOL

**Comment by teagan75** [comment]
Lol. The prices are based on how expensive it was to buy the seeds and how long to grow so getting it the vanilla way is too OP

**Comment by Ladysarajane** [comment]
I agree. Have you had baby zombies freezing? During day my map will show red dots and when I go to them....they are baby zombies. I can hit once or twice then they are invincible...but they can't move either. They will stay until the game is restarted then at night one or two will freeze again.

**Comment by teagan75** [comment]
Yeah I don't know what that is about
