### ISSUE TITLE
Trying to craft Plum seeds

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#20]
I have a different problem with the plum seeds this time. I am trying to craft the seeds, and JEI says I need 1 sugar, 4 collis seeds and 4 pumpkin seeds. When I go to craft them on the artisia crafting seeds, it accepts the sugar and collis seeds, but it won't accept the pumpkin seeds. Does my JEI have the recipe wrong? 
![2019-07-08_19 17 10](https://user-images.githubusercontent.com/34258851/60851735-86df0180-a1c2-11e9-8e3f-654fc612cf95.png)
You can see the pumpkin seed floating by the dirt. (I accidently hit that dirt picking up a seed, but after re-tilling and regrowing that plot, it still won't accept pumpkin seeds anywhere on it. 

Edit: I just tried to craft it in version 0.3.3 (my previous instance) and it crafted just fine. Same recipe. Not sure why it isn't crafting for me in version 0.4.2 hotfix.  :frowning_face:

**Comment by teagan75** [comment]
It doesn't work in a normal crafting table either?

Edit: Just checked and it doesn't. But I just crafted the plum seeds with the artisia plants. I thought it may have been something with converting the pumpkin seed bag to seeds but I tried those seeds specifically.

**Comment by teagan75** [comment]
You are tossing them on the ground correct? I assume so since you have the other items on the artisia plants

**Comment by Ladysarajane** [comment]
Yeah, placing them like I did in version 0.3.3. All the artesia plants are fully grown.
Tried daytime, nighttime and thought it might have been winter, waited for sunny spring day and no luck.

**Comment by Ladysarajane** [comment]
I had a thought. Didn't you make it so that the seeds can be crafted from the plums? Maybe that is blocking them from being crafted normally?

**Comment by teagan75** [comment]
Yes but I am in my instance and have the same recipes and it worked just fine. I am trying to think what would have happened with an update. I haven't messed much with that mod at all.

**Comment by Ladysarajane** [comment]
I'm confused too. I thought I was doing it wrong, so I went into the older instance and I was able to make it. Only difference is the new instance, I had to make a new world maybe old updated worlds aren't affected. If I get time tomorrow I'll create a test world world and try it.

**Comment by Ladysarajane** [comment]
*smacks head on desk* I found out why it wouldn't go. I had sugar cane growing near the artisia plot and one was diagonally touching the plot and that kept the pumpkin from placing. Once I removed it, I was able to make the seed.  Just cannot plant any other plants near the seeds.

**Comment by teagan75** [comment]
Wow! I will put a note in the questbook about that

**Comment by Ladysarajane** [comment]
I hadn't even thought of that as a problem...I was just trying to get my sprinkler to hit everything...LOL. Now we know. Now my Minecolonies has borked and I cannot remember the command to restore the backup for minecolonies. I didn't want to use a world backup...but looks like I might.

**Comment by teagan75** [comment]
https://wiki.minecolonies.com/source/systems/commands

**Comment by Ladysarajane** [comment]
It tells you had to make a backup, but not how to restore. Hmmm...I may have forgotten the colony id. I need to run some errands. I will try it when I get back. You think by now I would remember how to do it.

**Comment by Ladysarajane** [comment]
I had to take my game back to 10 Minecraft days. Oh, well. Now that I have me up to current, I seem to be missing a Harvest Festival Character Jim from the Animal Ranch. I checked everywhere. He didn't show up in the park for New Year's. Is there any way to recall him?

**Comment by teagan75** [comment]
You can pull him out of creative

**Comment by Ladysarajane** [comment]
Thanks got him back. I guess a barbarian must have got him. I really don't know where he had gone to.

**Comment by teagan75** [comment]
Maybe. They are supposed to respawn but.......

**Comment by Ladysarajane** [comment]
Yeah....He was missing 4 in-game days. I had a barbarian, but my guard got him...but he might have killed Jim first. First time I had one missing. I would say my builder built him in a wall....but my builder has been idle lately. Them builders don't care who they wall up...LOL 

Edit: Maybe we need a police dept to solve the case of Missing Jim...  :rofl:

**Comment by teagan75** [comment]
Going to close this issue
