### ISSUE TITLE
Freezing up after upgrading citizens hut

### ISSUE THREAD

**Issue by DodgerWoman26** [teagan75/Metamorphoses#21]
I didn't have a problem upgrading first two citizens huts to level 2 but after making it to city quests I went to upgrade a third and it keeps freezing on me once my builder completes it. The time still ticks but all animals and people freeze in place. When I try to quit to reload game- it crashes.

**Comment by teagan75** [comment]
Do you have a crash report?

**Comment by DodgerWoman26** [comment]
Another strange thing- I clicked to read crash report to copy and paste but it wouldn't pop up for me. Also I tried building a guard tower to see if that worked- crashed it again. No crash report again.

**Comment by teagan75** [comment]
The launcher doesn’t do a great job letting you view crash reports. You will need to open the instance folder and find the crash report folder.

**Comment by DodgerWoman26** [comment]
I looked- no crash report in instances either lol. Last one was from the 3rd but it crashed on me 3x yesterday. I can't figure it out- maybe a glitch with minecolonies- that one can be a pain, but it freezes all my cows and chickens which is harvest festival so I don't know. Messing around with it more today- still having the problem but today I tried sleeping after it froze the animals and people and it seemed to be fine after sleeping. Also then I was able to quit and reload without a crash lol. This one has me scratching my head. I guess a short term fix is just build all my building late in the day after I do my chores so I am not losing whole days :D

**Comment by teagan75** [comment]
you can try restoring a minecolonies backup from before the crashes. I had this happen to one of my worlds too. its usually minecolonies

**Comment by DodgerWoman26** [comment]
Is there just a back up for just minecolonies or do I need to restore a backup for my whole game. I looked in minecolonies folder didn't see a back up.

**Comment by teagan75** [comment]
In your save file there is a minecolonies folder with zip files labeled colonies. Those are backups. You will need to unzip one from before the crash and replace the colonies.dat file with the backup one.

**Comment by DodgerWoman26** [comment]
Well assuming I did it right- so far that seems to have worked lol. There is still a lag after a building completes before things start moving again but I will take that over a crash any day!
