### ISSUE TITLE
Minecolonies and spawn eggs

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#22]
With the lastest update....an unusual problem popped up. This won't be a problem once updates are done, but right now...I have all four herders..., swine,, chicken, and sheep and the cowboy. As predicted the animals disappeared with the update. I updated the quest book. I clicked on the repeatable quests and the did them and pulled the spawn eggs out of creative and I started putting them down....and my herders came out and killed them. They are level 1 herders...but they act as if the other animals are still there and come kill the new ones. I tried calling everyone to town hall...tried firing them and rehiring them...Restarting the pack...but they keep killing the new ones...(LOL my swineherder even killed pigs outside the pen area that happen to wander near them. 
Any idea's on how to reset them so they don't keep seeing invisible animals?

**Comment by teagan75** [comment]
I have had this happen and it wasn’t related to the mob spawning. I spammed a bunch of animals at once. Eventually it resolved itself.

**Comment by Ladysarajane** [comment]
It did resolve itself after a couple of restarts...in fact the invisible animals became visible... Until it resolved itself, I took away their axes LOL....and when those animals became visible, I gave them back. Do you have something in the quest book about reloading Lore data? All my pages disappeared again, so I reloaded before the game crashed.

**Comment by teagan75** [comment]
Glad it resolved for you! And there is no simple command to give pages back. You would have to know the data of the page. You can pull them out of the vanilla creative tab

**Comment by Ladysarajane** [comment]
My point is that, people may  need to know to reload Lore data so it doesn't cause the ticking entities again and crash games. Of course that is temporary until it is out of beta.

**Comment by teagan75** [comment]
I don’t think that should be an issue anymore. The files shipped with this last update as well as the last time. It doesn’t need to happen every time. No more lore pages will be added

**Comment by Ladysarajane** [comment]
Okay...that is good to know. This can be closed then.
