### ISSUE TITLE
Silver Coins

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#23]
I was finishing the Scholar quest that requires a book and a silver coin. I bought a silver coin from Johan and made the book, but the quest won't complete. The coins from Johan are Harvest Festival Coins but the quest requires Villagebox silver coins. How do I get those? I did complete the Farmer quest and it required the bronze coins, and it accepted the ones from Johan.

**Comment by teagan75** [comment]
Johan sells all the Village Box coins - at least he should

**Comment by Ladysarajane** [comment]
Omg...I am blind as a bat. Sorry about that. I have it now.
