### ISSUE TITLE
Can't find where to get Zinc

### ISSUE THREAD

**Issue by DodgerWoman26** [teagan75/Metamorphoses#25]
City quest for Crusher asks you to make a crusher and then steel blend and brass blend. Brass blend needs zinc. I looked in nether, mine and where to buy it. No luck.

**Comment by teagan75** [comment]
Zinc is a byproduct of crushing silver ore using the Crusher

**Comment by DodgerWoman26** [comment]
AHHHH!!! I had a feeling it was something so simple I was over looking it! UGH lol

**Comment by DodgerWoman26** [comment]
Are you sure it's silver ore- did a whole stack and got only lead as a byproduct.

**Comment by teagan75** [comment]
Oh no! I switched them 🤦‍♀️ I will have to put an update out. Sigh

**Comment by teagan75** [comment]
Just pushed an update v0.4.3_hotfix.  Copper will give zinc. I forgot to add that last update.

**Comment by DodgerWoman26** [comment]
Awesome! Well that was fast and thanks lol- been stuck on that one awhile :D

**Comment by teagan75** [comment]
no problem :D
