### ISSUE TITLE
More of a comment about Animal spawns in Quest Book. 

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#26]
I found that after updating the pack...and running the animal spawn commands again in the quest book.....If I restart the game...all my animals come back and I do not need spawn eggs. (and I mean reload it so the configs reload) Spawn eggs are unnecessary. If I try to use the spawn eggs prior to restarting the game, the animals don't show and if I restart the game then, then I have double the animals in the pens. I know this would be moot after beta...but maybe some info in the quest book about this?

**Comment by teagan75** [comment]
I will pin this issue at the very least

**Comment by DodgerWoman26** [comment]
I noticed this also- after reloading my game today lol. I now have double the animals.

**Comment by teagan75** [comment]
This shouldn't be an issue anymore with the release of version 1.0
