### ISSUE TITLE
City quest Rune of leap

### ISSUE THREAD

**Issue by DodgerWoman26** [teagan75/Metamorphoses#28]
Quest calls for dusts, 4 feathers, and a firework. There is no recipe to make the firework.

**Comment by teagan75** [comment]
the firework is the minecraft rocket/firework
![image](https://user-images.githubusercontent.com/12485764/61675699-fecb2280-acbe-11e9-9aeb-e4277ed59469.png)

**Comment by DodgerWoman26** [comment]
I figured it out. The icon is in N.E.I but not how to craft it. Amazingly I have never made a rocket before lol- I just googled the recipe.

**Comment by DodgerWoman26** [comment]
On another note- there is also no recipe for the pump pipes from steam advantage. You get 4 as a reward but if you break them they disappear and you can't make more. However you can make the pipes from power advantage and so far they have worked for me. You might want to make a note of it in the book. Took me a bit to figure it out as I was looking under the mod and for pump pipes lol.

**Comment by teagan75** [comment]
I was sure the pipes in my questbook were not pump pipes but the Power Advantage pipes. They look exactly alike and it’s confusing. The PA pipes are what you craft. The water pump makes their own pipes. I may see about hiding pump pipes from NEI

**Comment by DodgerWoman26** [comment]
I just checked and it was the steam powered water pump quest in city that gave me the pump pipes as a reward. Gives 6 pump pipes from steam advantage.  The last quest in that line- Distillation- gives 6 pipes from Power advantage. I think that's what confused me. So maybe remove the pump pipes from NEI and switch the reward in the earlier quest to the other pipes from power advantage to avoid any confusion.

**Comment by teagan75** [comment]
quest fixed for next version 0.4.4
