### ISSUE TITLE
Ender Lily seeds

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#29]
I am having trouble with the Ender Lily seeds. They teleport is obvious..but I didn't know how much..they have taken out several crops...but that isn't my problem...my problem is they get to a certain stage of growth and turn into Null seeds. (it seems when they try to go above 71% in growth)
![2019-07-24_10 49 05](https://user-images.githubusercontent.com/34258851/61803955-11e60b80-ae01-11e9-967e-348d9136fca2.png)
![2019-07-24_10 46 33](https://user-images.githubusercontent.com/34258851/61803988-1e6a6400-ae01-11e9-87dd-8f81d627eb37.png)

I cannot get the twine. The null seeds say they only grow in spring. Nothing says with the ender seeds that they are season specific.

**Comment by teagan75** [comment]
Wow. I have never had issues with the ender lily plants going null. I have grown them and harvested them. 

Try planting them in the Prefab Greenhouse. I believe I added that quest or suggested it but not sure when. 

Something messed with their growth. I never had them near my Harvest Festival crops. Also, I never had Agricraft water them. 

First, try isolating them in the greenhouse with no HF/HC crops around them.

**Comment by Ladysarajane** [comment]
After playing with them a bit...I think the null seeds are the HF plants that it has tried to land on. When they land on Agricraft plants..they just remove them and leave the crop sticks..but the ender seeds don't survive. I will try the greenhouse. I have the prefab farm...but not the greenhouse. Leave it to me..to find the weird stuff..LOL

**Comment by Ladysarajane** [comment]
Made the greenhouse...much better.

**Comment by DodgerWoman26** [comment]
I had the same problem lol. Quickly moved them to a side of my house away from my main crops and have had no issues since.
