### ISSUE TITLE
Metro quest- can't upgrade my citizen to Herbalist

### ISSUE THREAD

**Issue by DodgerWoman26** [teagan75/Metamorphoses#30]
The quest calls to upgrade your village box citizen to an Herbalist from a Alchemist. However when you get your citizen to Alchemist level the upgrade option goes away and just says maximal upgrades- no advanced upgrade.

**Comment by teagan75** [comment]
Huh. It works in my dev world. You are on the latest version?

**Comment by DodgerWoman26** [comment]
Version 0.4.3_hotfix lol I assume that's the latest version?

**Comment by DodgerWoman26** [comment]
I looked up village box in Mod list- says 1.10.2-0.6.0

**Comment by teagan75** [comment]
Ok, I double checked my configs and the herbalist is there. I will just make sure all the files move over for update 0.4.4 and hope it fixes itself

**Comment by teagan75** [comment]
Ok I am finally pushing update 0.4.4 through tonight
