### ISSUE TITLE
Capitol quest lines

### ISSUE THREAD

**Issue by DodgerWoman26** [teagan75/Metamorphoses#31]
Two quests- nether and titanium crops completed without me making them. Also missing descriptions and rewards. Same in building line- bakery and barracks. Also last crop for experience- no description or reward. A lot are missing descriptions- not sure if that was on purpose. A side note- I had to kill a wither boss a few times to get anything to open in Capitol line. Not sure if this was because I killed it the first 2 times with gun. Used machete last and it finally went through lol.

**Comment by teagan75** [comment]
Capital line isn't finished

**Comment by DodgerWoman26** [comment]
Well that makes sense :D Ok- perhaps I should slow down then LOL

**Comment by teagan75** [comment]
This quest line is finished in update 0.4.4
