### ISSUE TITLE
Banker

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#33]
Hi Teagan!
Hope you and your family are well. I was wondering if you are close to releasing an update to the pack. I have restarted my game, because my old game kept crashing...and I am up to the point of the bank again and I was wondering if it was close to releasing. Since my old game kept crashing, I deleted and started new and everything so far has worked well in the quests. Just the usually Harvest Fair problems such as the chicken festival not setting up properly, Chickens flipping between full grown and chicks stuff from that mod. Even the unique mod crops working better for me. I didn't remember the quest line with the recipes....but it worked for me too. Looking forward to future updates if you are doing them.

**Comment by teagan75** [comment]
We are well. I have been recovering from surgery since January and have just begun to get back into pack development. I know I was working on re-doing the bank and I may have an update ready to go. I will check my files and let you know.

**Comment by teagan75** [comment]
Oh I remember why I didn't do an update yet. Curse kept rejecting it but gave me no reason why and never answered my ticket. I finally figured it out with the help of my hubby. Two mods in the pack were removed from Curse so I can't have them in the pack. Plus I have to go an alter any recipes I changed using those mods.

**Comment by Ladysarajane** [comment]
Ah.....that is so frustrating. I wish it would have the reason for rejection. It would saved them a lot of support tickets for a simple automatic response that the Pack has mods not on curse.  Which mods were removed from curse?

**Comment by teagan75** [comment]
The augmented inferno and void mods

**Comment by Ladysarajane** [comment]
Not fun reworking the recipes. I hope you continue this mod pack. I really like it.

**Comment by teagan75** [comment]
Ok I finished an update tonight and am pushing it through. The bank should be fixed in version 0.4.4

**Comment by teagan75** [comment]
Ok I hate Twitch lol. The pack is still causing an error. It is on their side but they refuse to respond to me. I will put the update here under releases. Hopefully you know how to update a pack manually. The folders you need to change out are configs, minecolonies, mods and scripts.

**Comment by teagan75** [comment]
Well I figured it out for them FINALLY lol. The new update is on the launcher
