### ISSUE TITLE
Village box Version 4.4 causing crash on load

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#34]
I'm sorry Teagan...but the new update causes a crash...apparently with the Village Box mod. 
I attempted first with a fresh install and I received this error
[crash-2020-05-13_12.43.41-client.txt](https://github.com/teagan75/Metamorphoses/files/4623419/crash-2020-05-13_12.43.41-client.txt)

Then I tried updating my old instance and received the same error.

**Comment by teagan75** [comment]
I missed one comma in the json file lol. Oh well at least it was that and not a full world corruption. Going to push a hotfix now

**Comment by teagan75** [comment]
0.4.4_hotfix is live
