### ISSUE TITLE
Unable to download newest update

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#4]
I have been trying this for 3 hours now...I cannot update or download as new pack. It is like it can't find the files to download. Is anyone else having problems? I attempted to download Omnifactory and it downloaded fine. Is anyone else having problems?

**Comment by teagan75** [comment]
I know of one other person who had issues dl and also corrupt files. It’s kinda out of my hands since it’s handled by the launcher. Perhaps open a ticket with them?

**Comment by Ladysarajane** [comment]
Last ticket I had with them went unanswered for 3 weeks then it was a non-sense response... 😠 of course that was over a year ago.  I may have to do a complete reinstall of Twitch. Since their new format...getting into my Mods page has been real slow. Not sure when I am going to be getting the update ☹️ .
Edit: I submitted a ticket with Curse Forge...lets see how long it takes. I think they missed something putting it out.

**Comment by Ladysarajane** [comment]
I haven't heard about my ticket....but this morning it was delayed in the download...but I finally was able to both update to new profile..and to update my old profile (I wanted to make sure both worked). So this problem is solved. I myself think the paths to download it was messed up on their side. I have some errands to run this morning, but I am ready to play again 😺. Oh what is that music when the pack loads up? I love it. I call it music box music. Reminds me of a music box I had when I was little...until my older brother took it apart to see how it worked and it never would work again...LOL I need to tell him he still owes me one. 😆

**Comment by teagan75** [comment]
Glad you got the pack to dl properly! 

The mod that changes the music per biome, event or activity is https://minecraft.curseforge.com/projects/actualmusic?gameCategorySlug=mc-mods&projectID=266943

However, the music is by these guys and it’s royalty free too! https://www.youtube.com/channel/UCjMZjGhrFq_4llVS_x2XJ_w/about

**Comment by teagan75** [comment]
Also, I think the progression mod stopped working which means I do not think tin or lead drop from mining HF ores <sighs>. I have a fix in place for the next update if that is the case

Oh also, the Block Breaker used to harvest obsidian but I guess an update “fixed” that <sigh>. Thank goodness I go through the content every now and then to make sure things work.

**Comment by Ladysarajane** [comment]
I haven't had a chance to mine yet since updating....had a few errands to run and now this old body needs to rest a bit before I dive in. I know it did drop it before the update...I will keep my eye on it to see if I get it.

**Comment by Ladysarajane** [comment]
Playing the update, I have obtained  lead and tin in the mine. I am only down to the 3rd floor so far. Not sure how to get obsidian yet, so I haven't looked at the Block Breaker yet.

**Comment by teagan75** [comment]
That's good at least, but I think I will put my change in because I
realized there are more metals needed as the quests progress.
