### ISSUE TITLE
Medium Egg Quest won't complete

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#5]
The Quest under Hamlet to obtain Medium Egg. 
I finally obtained a medium egg from my chicken and the quest will not recognize it. I attempted manual submit as well and it will not recognize it.

**Comment by teagan75** [comment]
Hmm that is strange since the egg has no nbt or meta data. It’s straight up a medium egg. The small egg obviously worked. I will go and see what is up with it

**Comment by teagan75** [comment]
Nevermind, it does have NBT data. It records your relationship data, so I set the quest to ignore nbt data now for next update.

**Comment by Ladysarajane** [comment]
Okay, I was going to  report that my chicken laid a second medium egg and It still wasn't accepted. I wondered about NBT data. Will this affect the wool and milk? I am close to getting those.

**Comment by Ladysarajane** [comment]
The medium milk quest completed without problems. Still working on wool.

**Comment by teagan75** [comment]
Fixed in update 0.3.2
