### ISSUE TITLE
Unable to complete Hamlet quest line

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#6]
I finally got my sheep to give me medium wool.....I manually completed the egg quest, but now the last quest will not open...says I need the machete quest? Where is that I cannot find it. Nothing else is open to complete? 
![2019-06-14_09 24 23](https://user-images.githubusercontent.com/34258851/59513815-9dc35a00-8e89-11e9-8ae3-354ad9364046.png)

**Comment by teagan75** [comment]
Oh crap lol. I made a dependency on a quest in the next chapter - whoops! I probably moved a quest and forgot to remove the requirement

**Comment by Ladysarajane** [comment]
Can I complete that quest to open this last quest in this line so I can move on? What is that quest? Do I just need to make a machete?

**Comment by teagan75** [comment]
It won’t open if you make a machete until the next chapter is open. Just manually complete it for now and on your honor 😝 complete the requirements. I will fix it for next update. Hopefully today.

**Comment by Ladysarajane** [comment]
If you fix it today I can wait to try it out for testing purposes,  I have some landscaping I can do in the meantime. I am in winter...so besides garlic...I don't have much of a farm and I have been concentrating on relationships, upgrading minecolony buildings and mining. Quick question....if I buy buildings such as the harvest fair restaurant will that count when and if that quest line opens if I have already built  it?

**Comment by teagan75** [comment]
Unfortunately no because it wants to see the blueprint. It won't recognize
a completed building.If you buy them and wait to place them until the quest
opens then yes that will work

**Comment by Ladysarajane** [comment]
Good to know...I bought it, but was afraid to place it...Good thing I waited.

**Comment by teagan75** [comment]
This is fixed in update 0.3.2

Run the command /bq_admin default load to get the fixes in current game
