### ISSUE TITLE
Wooden channel valves

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#7]
Okay...I am in the village quest now and I am trying to complete the Farming guild quest...the Irrigation tasks and it asks for a OAK wooden channel valve.....I have made 4 of them...but they convert to Jungle wooden channel valves in my inventory and I can never complete the tasks. I don't have Jungle in my inventory at all. Oak irrigation channels is what I use to make them but it stays in my inventory a second then converts to jungle wood. I am at a lost. 
![2019-06-14_13 02 59](https://user-images.githubusercontent.com/34258851/59525624-d15fad80-8ea4-11e9-86a4-7062f92f8f90.png)
![2019-06-14_13 03 12](https://user-images.githubusercontent.com/34258851/59525630-d45a9e00-8ea4-11e9-9e13-856e9357b8aa.png)

**Comment by teagan75** [comment]
That’s a strange agricraft bug. When I tested that quest before it never happened. Guess I will have to have the quest recognize all the types. 

Edit: I could also try and fix the recipe with Crafttweaker. It might irritate people to have a Jungle channel and oak everything else hehe

**Comment by Ladysarajane** [comment]
Yeah...some people may get upset. I noticed that in this quest line, that if it completes an item say the irrigation channels and valves...and the quest recognizes it, if I put them in a chest to get more room in my inventory, the items for that part uncompletes (for example levers)  I notice this on upgrading the builder too. (I already had my builder upgraded, I was just collecting the items). I didn't notice this on previous quest lines. I am going to go in creative and give me an oak channel valve to complete the quest (and make my builds pretty) 😺

**Comment by teagan75** [comment]
That’s Better Questing. Most of the quests are retrieval so if, for instance, you buy the Cafe ahead of time you can still complete it later. Only crafting quests keep the complete.

**Comment by teagan75** [comment]
Was not able to fix the recipe via crafttweaker. I changed the quest to ignore the nbt data which was causing the issue.

**Comment by Ladysarajane** [comment]
Does that mean we can't craft the Oak ones? If so maybe give a couple of them for rewards?

**Comment by teagan75** [comment]
actually correction I got the recipes to work with crafttweaker. This only
happens with the channel valve correct?

**Comment by Ladysarajane** [comment]
Yes that is the only one I had trouble with

**Comment by teagan75** [comment]
this should be fixed in version 0.3.3
