### ISSUE TITLE
Black Quartz recipe conflict.

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses#9]
I was attempting to make a coal generator and black quartz at this time is suppose to be made by smelting quartz. I made the quartz and smelted it and now I have silicon.

**Comment by teagan75** [comment]
Oh thank you! I kept getting a script error about a conflicting recipe for quartz but couldn’t locate it lol. I will remove the silicon recipe now from the furnace and put it to something else. The pack needs black quartz before silicon 😝

**Comment by Ladysarajane** [comment]
Love testing! 😄  Refined storage was the culprit I bet!

**Comment by teagan75** [comment]
Ah yes I am just getting into writing quests for that mod so I will be changing the silicon to a recipe created in another machine. Easy enough! Hehe

**Comment by Ladysarajane** [comment]
Is it going to be a while for the next update? Debating if I should give myself the black quartz to finish the quest.

**Comment by teagan75** [comment]
I could put out a small update today with the new scripts

**Comment by Ladysarajane** [comment]
That would be great if it isn't too much trouble. I know it's Father's Day and you JJ and Jerle want to celebrate like we are. Although we are about to build an Ark here...had so many severe storms and rain. We had 3.5 inches of rain since midnight and expecting more today.

**Comment by teagan75** [comment]
Us too! We are just chillin' cause we did a big thing yesterday. My hubby
is actually seeing if he can port Harvest Festival to 1.12.2 - no promises
but I am so hopeful for this :D If it works then we can look into fixin
some of the bugs too!

I have just saved my stuff and will be exporting it to Curse soon.

**Comment by Ladysarajane** [comment]
That would be great if he could port it. Keeping my fingers crossed! We planned for a cookout today,.. but that is impossible so we are cooking indoors. Luckily it isn't to hot for indoor cooking. I just have to keep shutting down electronics as storms roll over us.   We had to put a drain line on our above-ground pool because it is overfilled from the rain. 

Tell Jerle to have a Happy Father's Day...And hope he is successful with that port and thank you for putting out that update today. 😃

**Comment by Ladysarajane** [comment]
You can close this now...the update works great! made my coal generator and working on other things in between the storms. They've issued another severe thunderstorm watch again 🙄 so I'll be off and on.

Loving the alchemical makers...just made the redstone one...pretty nifty.

**Comment by teagan75** [comment]
fixed in version 0.3.3
